composer.json

Create a composer.json file so that the theme can be required by composer

---

source/_meta/_00-head.twig
source/_patterns/01-atoms/04-images/logo.twig
source/_patterns/01-atoms/08-video/video.yml
source/_patterns/01-atoms/09-menu/tab/tab.twig
source/_patterns/01-atoms/09-menu/tab/tab.yml
source/_patterns/02-molecules/menus/tabs/_tabs.scss
source/_patterns/02-molecules/menus/tabs/tabs.js
source/_patterns/02-molecules/menus/tabs/tabs.md
source/_patterns/05-pages/_styleguide-specific.scss
source/css/pattern-scaffolding.css

Fix for http://localhost:3002/pattern-lab/public/?p=molecules-tabs

javascript tab fixes

---

package.json

https://github.com/fourkitchens/emulsify/issues/15

15: added step to remove current PL installation on install

---

components/_twig-components/filters/clean_class.filter.php
components/_twig-components/filters/safe_join.filter.php
components/_twig-components/filters/t.filter.php
components/_twig-components/filters/without.filter.php
components/_twig-components/functions/kint.function.php
components/_twig-components/functions/link.function.php
components/_twig-components/tags/trans.tag.php
emulsify.theme

Fixes Drupal PHP codings standards errors.

Drupal coding standards for PHP

---

gulpfile.js

Fixes some js code style issues in gulpfile.js.

Fix eslint errors

---

docs/gulp-config.md

Dependent on https://github.com/fourkitchens/emulsify-gulp/pull/16

gulp testing documentation addition

---

components/_patterns/00-base/_breakpoints.scss
components/_patterns/00-base/_outer-layout.scss
components/_patterns/00-base/layouts/grid/_grid.scss
components/_patterns/01-atoms/05-forms/textfields/_textfields.scss
components/_patterns/01-atoms/09-menu/tab/_tab.scss
components/_patterns/02-molecules/info-box/_info-box.scss
components/_patterns/02-molecules/menus/inline-menu/_menu.scss
components/_patterns/02-molecules/menus/tabs/_tabs.scss
components/_patterns/02-molecules/pager/_pager.scss

Changed the current sizes:
```
small
small-med
small-large
medium
large
```
to a more generic:
```
xs
small
medium
large
xl
```

Updated breakpoints to t-shirt sizes.

---

components/_patterns/00-base/layouts/grid/00-grid.twig
components/_patterns/01-atoms/01-links/link/link.twig
components/_patterns/01-atoms/02-text/00-headings/heading-1/heading-1.twig
components/_patterns/01-atoms/02-text/00-headings/heading-2/heading-2.twig
components/_patterns/01-atoms/02-text/00-headings/heading-3/heading-3.twig
components/_patterns/01-atoms/02-text/00-headings/heading-4/heading-4.twig
components/_patterns/01-atoms/02-text/00-headings/heading-5/heading-5.twig
components/_patterns/01-atoms/02-text/00-headings/heading-6/heading-6.twig
components/_patterns/01-atoms/02-text/text/01-paragraph.twig
components/_patterns/01-atoms/02-text/text/02-blockquote.twig
components/_patterns/01-atoms/02-text/text/_text.scss
components/_patterns/01-atoms/02-text/text/paragraph.yml
components/_patterns/01-atoms/03-lists/02-definition.twig
components/_patterns/01-atoms/03-lists/_list-item.twig
components/_patterns/01-atoms/05-forms/checkbox/_checkbox-item.twig
components/_patterns/01-atoms/05-forms/checkbox/checkbox.twig
components/_patterns/01-atoms/05-forms/radio/_radio-item.twig
components/_patterns/01-atoms/06-buttons/01-button.twig
components/_patterns/01-atoms/06-buttons/01-button~alt.yml
components/_patterns/01-atoms/06-buttons/02-button~alt-2.yml
components/_patterns/01-atoms/08-video/video.twig
components/_patterns/02-molecules/card/01-card.twig
components/_patterns/02-molecules/card/_card.scss
components/_patterns/02-molecules/card/card.yml
components/_patterns/02-molecules/card/card~bg.yml
components/_patterns/02-molecules/info-box/info-box.twig
components/_patterns/03-organisms/card-grid/card-grid.yml
components/_patterns/03-organisms/card-grid/card-grid~alt.yml
docs/orientation.md

- Simplified/fixed blockname and modifier Twig syntax on default patterns
- Documented syntax for more robust approach

Blockname modifiers

---

components/_patterns/05-pages/_page.scss

Addresses https://github.com/fourkitchens/emulsify/issues/85

Bugfix: layout styling inconsistencies

---

README.md
components/_data/data.json
components/_data/listitems.json
components/_patterns/01-atoms/04-images/00-image/image.yml
components/_patterns/01-atoms/04-images/icons/_icon_sprite.scss
components/_patterns/02-molecules/card/card.yml
components/_patterns/03-organisms/card-grid/card-grid.yml
components/_patterns/03-organisms/card-grid/card-grid~alt.yml
components/_patterns/05-pages/example/example.twig

- changes img urls to https
- adds demo link in readme

Fixes for https://fourkitchens.github.io/emulsify/pattern-lab/public/ demo

---

components/_patterns/00-base/_breakpoints.scss
components/_patterns/00-base/_mixins.scss
components/_patterns/00-base/layouts/grid/_grid.scss
components/_patterns/01-atoms/02-text/00-headings/_headings.scss
components/_patterns/01-atoms/04-images/icons/_icon_sprite.scss
components/_patterns/01-atoms/06-buttons/_buttons.scss
components/_patterns/02-molecules/card/_card.scss
components/_patterns/02-molecules/info-box/_info-box.scss
components/_patterns/04-templates/example/_example.scss
components/_patterns/04-templates/example/example.twig
components/_patterns/05-pages/_page.scss
components/_patterns/05-pages/example/example.twig

- fixing stylelint errors 
- This includes adding a sass file in `components/_patterns/04-templates` (otherwise, it throws an error)
- Also simpler wrapper mixin and better sizing while I was in there

Stylelint issue fixes

---

.stylelintrc
components/_patterns/01-atoms/05-forms/select/_select.scss
package.json

Depends on https://github.com/fourkitchens/emulsify-gulp/pull/42
To test:
TODO:

Changes necessary after dependency updates

---

components/_meta/_00-head.twig
components/_meta/_01-foot.twig
components/_patterns/00-base/global/global.js
components/_patterns/02-molecules/accordion-item/accordion-item.js

Javascript usage needed some love.

Better commenting of js, adding symlink, behaviors approach

---

yarn.lock

Update emulsify gulp version number in the yarn.lock file.

Update yarn.lock w/emulsify gulp

---

templates/navigation/menu-local-action.html.twig

Issue fixed Twig_Error_Loader: Template "@atoms/03-lists/list-item.twig" is not defined

Issue fixed Twig_Error_Loader

---

package.json

Fixes https://github.com/fourkitchens/emulsify/issues/120

changed to reference dpl fork of pattern lab

---

README.md

Added single line standalone installation instructions as well as fixed, cleared up Drupal instructions

installation readme clarification, fixes

---

gulpfile.js

I was playing around with overrides and got no errors when running gulp. Super small PR to help a little with that.

Show errors from local gulp file if any

---

components/_patterns/05-pages/_page.twig

(closing '.main-content' div, and not '.layout-content')

fixing typo in a comment

---

README.md

Adds a link in the README to this playlist of Emulsify videos: https://www.youtube.com/playlist?list=PLO9S6JjNqWsGMQLDfE8Ekt0ryrGa3g4km
Solves #173.

Docs: Add video playlist

---

components/_patterns/01-atoms/images/image/_image.scss
components/_patterns/01-atoms/images/image/image.twig
components/_patterns/01-atoms/images/image/image.yml

This PR introduces the image component in our current latest state.

Restart: Images

---

gulpfile.js

See https://github.com/fourkitchens/emulsify/issues/183

remove unnecessary iife

---

.gitignore

Like it says on the tin.
`**/bem.function.php` was in there twice, so I removed one of them

Removed duplicate line from .gitignore.

---

components/_data/paths.json
components/_patterns/01-atoms/04-images/icons/_icon.twig
components/_patterns/01-atoms/04-images/icons/icons.twig
components/_patterns/01-atoms/04-images/icons/icons.yml
components/_twig-components/functions/pl_attach-library.function.php

- Simplifies Drupal/PL icon paths.
- Fixes PL-specific attach_library function

Improved icon components.

---

components/_data/paths.json

in case PL is running within a drupal theme - get dist correct location

---

package.json

See https://github.com/fourkitchens/emulsify-gulp/pull/86 for details and testing instructions.

Remove unused clean task

---

components/_patterns/00-base/global/01-colors/_color-vars.scss
components/_patterns/00-base/global/01-colors/_colors-used.scss
components/_patterns/00-base/global/animations/_animation.scss
components/_patterns/00-base/global/base/_pl-base.scss
components/_patterns/01-atoms/01-links/link/_link.scss
components/_patterns/01-atoms/02-text/00-headings/_headings.scss

This PR includes:
- New comments in color file
- Moving some variables to components
- Fixes animation css
- Adds margin around all patterns
- Uses `$color-heading` for the default color in the headings

Random styleguide tweaks

---

components/_patterns/01-atoms/07-tables/_tables.scss

Fix for https://github.com/fourkitchens/emulsify/issues/185.

185: Table support for headers in columns

---

emulsify.php

Found and fixed a very minor typo in an error about write permissions in emulsify.php.

Typo in error message

---

package-lock.json
yarn.lock

Companion to https://github.com/fourkitchens/emulsify-gulp/pull/99

lock file updates
