fourkitchens/emulsify

- components/_patterns/00-base/layouts/grid/00-grid.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-1/heading-1.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-1/heading-1.yml
- components/_patterns/01-atoms/02-text/00-headings/heading-2/heading-2.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-2/heading-2.yml
- components/_patterns/01-atoms/02-text/00-headings/heading-3/heading-3.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-3/heading-3.yml
- components/_patterns/01-atoms/02-text/00-headings/heading-4/heading-4.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-4/heading-4.yml
- components/_patterns/01-atoms/02-text/00-headings/heading-5/heading-5.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-5/heading-5.yml
- components/_patterns/01-atoms/02-text/00-headings/heading-6/heading-6.twig
- components/_patterns/01-atoms/02-text/00-headings/heading-6/heading-6.yml
- docs/drupal-components.md
- templates/content/page-title.html.twig
Simple update to headings so that you can use an h2 and an h3 for example in the same pattern, and not have issues with them both being called {{ heading }}.
> Namespaced headings so that more than one can be used in a pattern.

- components/_patterns/01-atoms/04-images/01-logo/logo.twig
**This PR:**
- Adds comments, and variables to logo component.
Should the logo component be moved to Molecules since it contains two atoms (link and image)?
I think conceptually, it makes sense to group it with images, but it also makes sense to categorize it as a molecule.
> Logo Cleanup

- components/_twig-components/filters/t.filter.php
- Add a better t filter to pattern lab so it plays well with Drupal
- While looking at the pager example I noticed that someone had copied and pasted a Drupal template.
- I then realized that the t function we were using in Pattern lab didn't support string replacements.
- Now it does.
- We should discuss if we are merging straight to master or using the develop branch.  I recently updated the `develop` branch because it was very out of date against `master`
- Looks like other functions we might want to implement are found here: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Template%21TwigExtension.php/class/TwigExtension/8.2.x
- Another Drupal.Org page: https://www.drupal.org/docs/8/theming/twig/functions-in-twig-templates
- Go to the pager molecule and hover over the …
> Add a better t filter to pattern lab so it plays well with Drupal

- package.json
Depends on https://github.com/fourkitchens/emulsify-gulp/pull/37
**To test:**
To-do:
> moved stylint dep to emulsify-gulp

- emulsify.drush.inc
- Add basic drush script to create a subtheme
- Decided not to go with the "kit" approach and used the source directory.
- Edited the source files directly (we may need to replace more specific patterns if anything is broken)
- Added a `--slim` option to use a smaller number of files
- Seems like the post install is working for pattern lab ... maybe we don't need this?
> Add basic drush script to create an Emulsify based theme

- package.json
- yarn.lock
As a result of a pre-commit script being added in https://github.com/fourkitchens/emulsify-gulp/pull/49 we need to add `precommit.silent` so that we don't get notices.
...point emulsify-gulp to the repo instead of the branch.
> Add precommit.silent to prevent notices from emulsify-gulp

- components/_patterns/01-atoms/01-links/link/link.twig
- components/_patterns/01-atoms/02-text/00-headings/_heading.twig
- components/_patterns/03-organisms/_node.twig
- components/_twig-components/functions/bem.function.php
- components/_twig-components/functions/render_attributes.function.php
@evanmwillhite here is essentially what I demoed for you earlier. I'm not 100% satisfied with it. I'd like it to work better with existing Twig methods for manipulating attributes. It already does sorta but not to the point it can do away with the `additional_attributes` object and still be able to produce the desired results. Also, as I mentioned, I'm not sure if there are any consequences for removing attributes from `$context['attributes']` like this does.
> Attribute handling take 2

- scripts/pattern_lab.sh
This will have Emulsify use [Drupal Pattern Lab's PL Edition](https://github.com/drupal-pattern-lab/edition-php-twig-standard) instead of [the original, abandoned PL Edition](https://github.com/pattern-lab/edition-php-twig-standard). This has lots of improvements over the old one and @evanmwillhite is a core maintainers of it as well (as am I along with @sghoweri).
Cheers; congrats on launching the new version! Happy Pattern Labbing!
> Use Drupal Pattern Lab's version of Pattern Lab

- components/_patterns/02-molecules/menus/_menu-item.twig
- components/_patterns/02-molecules/menus/_menu.twig
- templates/block/block--mainnavigation.html.twig
Learning curve on client project provided:
1. Better handling of classes for inheritance. Basically, Drupal doesn't have a `<li>` level template, so we are including the outer element and need a way to pass classes into the child element. This method allows passing the `<ul>` modifiers and blockname to the `<li>`s.
2. Main menu files provide `<nav>` element so we need to override the default drupal file that provides its own
> Main Menu Fixes

- scripts/pattern_lab.sh
Addresses https://github.com/fourkitchens/emulsify/issues/155
> Switch back to core pattern lab

- components/_patterns/01-atoms/04-images/00-image/image.twig
There is currently a bug where when using the image field in certain Drupal templates, the img_url link option will accidentally inherit the image's attribute values (e.g., when using it in Drupal's default image.html.twig file).
This additions clears the attributes object for that specific link instance (only within the image file) since we pass the options manually to that link anyway.
> Image field link Attributes fix

- components/_patterns/01-atoms/06-buttons/01-button.twig
If a button is used in a place that doesn't require a href, such as a form, it shouldn't have an empty `href=""`.
> Add conditional for button_url

- .gitignore
- package.json
Fixes github pages deployment script (`gulp ghpages-deploy`) by switching from gulp-gh-pages to gh-pages npm package. This PR merely ignores the build directory created by the script - the majority of the change is in https://github.com/fourkitchens/emulsify-gulp/pull/74
**To test:**
> Github Pages deployment fix

- emulsify.php
Apparently I pushed this to the wrong repo.  Let me know if I should reopen this from Emulsify for consistency
- https://github.com/fourkitchens/emulsify/issues/182
- Mess around with all the command line options:
```
'arguments' => array(
'human_readable_name' => 'The name of your theme.',
),
'options' => array(
'machine-name' => 'The machine-readable name of your theme. This will be auto-generated from the human_readable_name if ommited.',
'description' => 'The description of your theme',
'path' => 'Supports three options contrib, custom, none.  Defaults to "custom".',
'slim' => 'Only copy base files',
),
```
- Example:
`php emulsify.php test2 --slim --machine-name awesome3 --path contrib --description "My really awesome description"`
`php emulsify.php -h` # for help
- I got tired of …
> Get rid of drush and use a plain PHP script for scaffolding

- components/_patterns/01-atoms/04-images/icons/_icon.twig
- components/_patterns/01-atoms/04-images/icons/icons.md
- components/_twig-components/functions/pl_attach-library.function.php
If you want to use this in PL files (which we do in new icon file), this function has to be added to Pattern Lab's `_twig-components`
**How to test:**
1. Checkout this branch and run `yarn start` and make sure you get no errors
2. Bonus points: Ensure it causes no issues in Drupal (I tested this)
> Added attach_library Twig function in PL

- components/images/README.md
- images/README.md
Added a couple of READMEs to the image directories for clarity. Addresses #223
> 223: Clarify image directory usage

- emulsify.php
- Follow up to this PR: https://github.com/fourkitchens/emulsify/pull/218
- Fix php script help command output (Examples section)
- The readme has already been updated so no changes necessary here
- Push code
- Change directories into the theme directory
- Run `php emulsify.php -h`
- Notice this text before the change:
```
$ php emulsify.php -h
This command will create an Emulsify theme. See examples to get started.
Arguments
human_readable_name => The name of your theme.
Options
machine-name => The machine-readable name of your theme. This will be auto-generated from the human_readable_name if ommited.
description => The description of your theme
path => Supports three options contrib, custom, none.  Defaults to "custom".
slim => Only copy base files
Examples
machine-name => The …
```
> Fix help command output

- components/_meta/_00-head.twig
Pattern Lab still references the old `pattern-scaffolding.css` file that was removed in https://github.com/fourkitchens/emulsify/pull/236. This simply removes that unneeded line.
> Remove old PL CSS ref

- components/_patterns/01-atoms/09-menu/tab/_tab.scss
- components/_patterns/01-atoms/09-menu/tab/tab.twig
Fixes https://github.com/fourkitchens/emulsify/issues/237
- Removes tab class for non-JS (Drupal) implementations like local tasks.
- Adds styling to both classes so they look the same
> 237: removed JS class on non-JS implementation

- components/_patterns/00-base/global/base/_02-breakpoints.scss
- components/_patterns/00-base/layouts/_default.scss
- components/_patterns/05-pages/article/article.twig
- components/_patterns/style.scss
Addresses https://github.com/fourkitchens/emulsify/issues/244
Along with https://github.com/fourkitchens/emulsify-gulp/pull/78, this PR removes singularity for layout and replaces it with a flexbox implementation with a CSS Grid one commented out.
**What it does**
1. Removes singularity references and implementation in main layout file
2. Implements a simple flexbox layout instead
3. Adds a CSS Grid layout that is commented out
**To Test**
1. Checkout this branch and link the Emulsify Gulp instance with the corresponding branch
2. View the [sidebar template](http://localhost:3000/pattern-lab/public/?p=templates-with-sidebar) and [full-width template](http://localhost:3000/pattern-lab/public/?p=templates-full-width) and ensure content is displayed correctly at all screen sizes
> 244: Remove Singularity

- components/_patterns/01-atoms/06-buttons/01-button.twig
Resolving #263.
If there is a link inside the button, it switches it into <a> element, because it only needs to look like a button but behave like a link.
I added twig brackets to print partial elements {{ "<a" }}, because it seemed a "cleaner" way of doing it, but the same result can be achieved without these brackets.
> Replacing <button> element with <a href> whenever there's a link

- components/_patterns/02-molecules/menus/inline-menu/_inline-menu.scss
(This is affecting links at the footer, that otherwise get the default blue color from the browser)
> Adding a default color to inline menu link

- components/_patterns/00-base/global/base/_04-base.scss
- components/_patterns/02-molecules/menus/inline-menu/_inline-menu.scss
This PR resolves #297.
_Why aren't any of the components impacted?_ Because Pattern Lab already applies border-box.
> Default to border-box; Fix linting

- components/_patterns/02-molecules/menus/_menu-item.twig
**Description:**
Implements the great patch proposed in https://github.com/fourkitchens/emulsify/issues/222#issue-320862096 to ensure original menu item modifiers get passed down but not ones that are specific to a specific level (e.g., `main-menu__item--with-sub`)
**To review:**
- Before checking out this branch, view the source of the [Main Menu](http://localhost:3000/pattern-lab/public/?p=molecules-main-menu) and verify that every dropdown child incorrectly has the class `main-menu__item--with-sub`
- Checkout this branch and verify that only the dropdown items _with_ a dropdown below them have that class.
> 222: removed inheritance of ALL item modifiers

- .stylelintrc
- components/_patterns/00-base/global/base/_pl-base.scss
- package-lock.json
- yarn.lock
Stylelint has updated and we are getting some errors now. This fixes those:
- Ignore `no-descending-specificity` in stylelintrc (seems confused with nested SCSS styles like `::last-child`)
- One PL-specific font style was missing
Also package-lock/yarn-lock needed to be updated for emulsify-gulp 4.0.0
> Minor 3.x fixes

- components/_patterns/02-molecules/menus/main-menu/_00-main-menu.scss
- components/_patterns/02-molecules/menus/main-menu/main-menu.twig
**Description:**
- Move icon per the recommendations [here](http://www.a11ymatters.com/pattern/mobile-nav/) (also show nav)
- Also moves some styling to the correct place (fixing the position and giving it a 100% height) that was on the wrong element.
To Test:
- Verify the [Main Menu](http://localhost:3000/pattern-lab/public/?p=molecules-main-menu) still functions as it should
> 291: move icon inside navigation
